version: "3"
services:
  strapi-backend:
    container_name: strapi-backend
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: backendlabicn:latest
    restart: unless-stopped
    env_file: .env
    environment:
      # Database
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgresdb
      DATABASE_PORT: 5432
      DATABASE_NAME: strapidb
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

      # Application
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: production
    volumes:
      - photo-data:/opt/app/public/uploads

    ports:
      - "1337:1337"
    networks:
      - backendNetwork
    depends_on:
      - postgresdb

  postgresdb:
    container_name: postgresdb
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: strapidb
    volumes:
      - db-data:/var/lib/postgresql/data/

    networks:
      - backendNetwork

volumes:
  db-data:
  photo-data:

networks:
  backendNetwork:
    name: BackendNetwork
    driver: bridge
